import logging
from typing import Optional

import openai
from openai import OpenAI, APIError, RateLimitError, AuthenticationError

from app.config import settings

logger = logging.getLogger(__name__)

# Initialize OpenAI client
try:
    client = OpenAI(api_key=settings.OPENAI_API_KEY)
except Exception as e:
    logger.error(f"Failed to initialize OpenAI client: {str(e)}")
    raise

async def generate_cards_with_ai(
    text: str,
    model_name: str = settings.OPENAI_MODEL_NAME,
    system_prompt: Optional[str] = None,
) -> str:
    """
    Generate flashcards using OpenAI's chat completion API.
    
    Args:
        text: The input text to generate flashcards from
        model_name: The OpenAI model to use (defaults to settings.OPENAI_MODEL_NAME)
        system_prompt: Optional custom system prompt to override default
        
    Returns:
        str: The raw text content generated by the AI
        
    Raises:
        APIError: If there's an error with the OpenAI API
        ValueError: If the input text is empty or too long
    """
    if not text or len(text.strip()) == 0:
        raise ValueError("Input text cannot be empty")
        
    try:
        messages = [
            {"role": "system", "content": system_prompt or settings.DEFAULT_SYSTEM_PROMPT},
            {"role": "user", "content": text}
        ]
        
        response = await client.chat.completions.create(
            model=model_name,
            messages=messages,
            temperature=0.7,
            max_tokens=2000,  # Adjust based on needs
        )
        
        return response.choices[0].message.content
        
    except APIError as e:
        logger.error(f"OpenAI API error: {str(e)}")
        raise
    except RateLimitError as e:
        logger.error(f"OpenAI rate limit error: {str(e)}")
        raise
    except AuthenticationError as e:
        logger.error(f"OpenAI authentication error: {str(e)}")
        raise
    except Exception as e:
        logger.error(f"Unexpected error in generate_cards_with_ai: {str(e)}")
        raise 